## 5-1. 그룹별로 요약하여 데이터 확인
* value_counts(), groupby(), pivot_table()

In [2]:
sample_file = 'data/sales_sample.csv'

In [3]:
# 샘플 파일 로딩
import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df.head()

   지역   상품  판매수량   매출
0  서울  노트북     2  120
1  서울  태블릿     1   80
2  부산  노트북     2  100
3  부산  태블릿     1   70
4  서울  노트북     3  150

In [4]:
# 지역별 판매 기록의 개수
sample_df.지역.value_counts()

지역
서울    7
부산    7
대전    6
Name: count, dtype: int64

In [5]:
# 상품별 판매 기록의 개수와 비율
sample_df.상품.value_counts()

상품
노트북    10
태블릿    10
Name: count, dtype: int64

In [6]:
sample_df.상품.value_counts(normalize=True)

상품
노트북    0.5
태블릿    0.5
Name: proportion, dtype: float64

In [7]:
# 지역과 상품의 조합별 판매 기록 개수
sample_df.value_counts(['지역', '상품'])

지역  상품
서울  노트북    4
부산  태블릿    4
서울  태블릿    3
부산  노트북    3
대전  노트북    3
    태블릿    3
Name: count, dtype: int64

In [8]:
# 지역별 총매출
sample_df.groupby('지역')['매출'].sum()

지역
대전    585
부산    850
서울    850
Name: 매출, dtype: int64

In [9]:
# 상품별 평균 매출
sample_df.groupby('상품')['매출'].mean()

상품
노트북    112.5
태블릿    116.0
Name: 매출, dtype: float64

In [10]:
# 지역별 판매수량의 합계와 매출의 합계
sample_df.groupby('지역')[['판매수량', '매출']].sum()

    판매수량   매출
지역
대전    11  585
부산    13  850
서울    13  850

In [11]:
# 지역별 매출의 건수, 합계, 평균, 최대값
sample_df.groupby('지역')['매출'].agg(['count', 'sum', 'mean', 'max'])

    count  sum        mean  max
지역
대전      6  585   97.500000  135
부산      7  850  121.428571  210
서울      7  850  121.428571  160

In [12]:
# 지역과 상품별 평균 매출
sample_df.pivot_table(
    index = '지역',
    columns = '상품',
    values= '매출',
    aggfunc= 'mean'
)

상품    노트북         태블릿
지역
대전  105.0   90.000000
부산  120.0  122.500000
서울  112.5  133.333333

In [13]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시

## 5-2. 결측치 처리

In [14]:
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [15]:
# 컬럼별 결측치 갯수 확인
sample_df.isnull().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [16]:
# 컬럼별로 결측치가 있는지의 여부 확인
sample_df.isnull().any()

Name      False
Age        True
Gender    False
City       True
dtype: bool

In [17]:
# 'Age' 컬럼에 결측치가 몇개 있는지 확인
sample_df['Age'].isnull().sum()

np.int64(2)

In [18]:
# 'Age' 컬럼에 결측치가 있는 행 확인
sample_df[sample_df['Age'].isnull()]

     Name  Age Gender         City
1     Bob  NaN      M  Los Angeles
4  Edward  NaN      M      Houston

In [19]:
# 결측치가 하나라도 있는 행 추출
sample_df.isnull().any(axis=1)

0    False
1     True
2     True
3    False
4     True
5    False
6    False
dtype: bool

In [20]:
sample_df.isnull().any(axis=1).sum()

np.int64(3)

In [21]:
# 결측치가 하나라도 있는 행 삭제
sample_df.dropna()

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

In [22]:
# 'City' 컬럼에 결측치가 있는 행 삭제
sample_df.dropna(subset=['City'])

     Name   Age Gender         City
0   Alice  24.0      F     New York
1     Bob   NaN      M  Los Angeles
3   David  29.0      M      Chicago
4  Edward   NaN      M      Houston
5   Alice  24.0      F     New York
6   Susan  32.0      F      Houston

In [23]:
# 'Age' 컬럼의 결측치를 평균값으로 채우기
sample_df['Age'] = sample_df['Age'].fillna(sample_df['Age'].mean())
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

## 5-3. 중복값 처리하기

In [24]:
# 결측치가 있어서 duplicate으로 추출되지 않을 수 있어서
# 결측치 제거 후 중복 여부 확인


# 중복값인 행 확인
sample_df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [25]:
sample_df.duplicated(keep=False).sum()

np.int64(2)

In [26]:
# 중복값인 행 추출
sample_df[sample_df.duplicated(keep=False) ]

    Name   Age Gender      City
0  Alice  24.0      F  New York
5  Alice  24.0      F  New York

In [27]:
# 중복값인 행 삭제
sample_df.drop_duplicates()

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
6    Susan  32.0      F      Houston

In [28]:
# 이름, 도시에 중복이 있는지 확인
sample_df[['Name', 'City']].duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [29]:
# 이름, 도시가 중복인 행 추출
sample_df[sample_df[['Name', 'City']].duplicated()]

    Name   Age Gender      City
5  Alice  24.0      F  New York

In [30]:
# 이름, 도시가 중복인 행 삭제
sample_df.drop_duplicates(subset=['Name', 'City'])

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
6    Susan  32.0      F      Houston

## 타이타닉 데이터 실습

In [31]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(titanic_data, sep='\t')
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [32]:
# 컬럼명을 소문자로 변경
titanic_df.rename(columns=str.lower)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [33]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [34]:
# 'age' 컬럼의 결측치 수
titanic_df.Age.isnull().sum()

np.int64(30)

In [35]:
# 'age' 컬럼이 결측치인 행
titanic_df[titanic_df.Age.isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.0500,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
107,108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [36]:
# 'age' 컬럼이 결측치인 사람들의 이름
titanic_df[titanic_df['Age'].isnull()][['Name', 'Age']]

                                               Name  Age
5                                  Moran, Mr. James  NaN
17                     Williams, Mr. Charles Eugene  NaN
19                          Masselmani, Mrs. Fatima  NaN
26                          Emir, Mr. Farred Chehab  NaN
28                    O'Dwyer, Miss. Ellen "Nellie"  NaN
29                              Todoroff, Mr. Lalio  NaN
31   Spencer, Mrs. William Augustus (Marie Eugenie)  NaN
32                         Glynn, Miss. Mary Agatha  NaN
36                                 Mamee, Mr. Hanna  NaN
42                              Kraeff, Mr. Theodor  NaN
45                         Rogers, Mr. William John  NaN
46                                Lennon, Mr. Denis  NaN
47                        O'Driscoll, Miss. Bridget  NaN
48                              Samaan, Mr. Youssef  NaN
55                                Woolner, Mr. Hugh  NaN
64                            Stewart, Mr. Albert A  NaN
65                         Moubarek, Master. Gerios  NaN
76                                Staneff, Mr. Ivan  NaN
77                         Moutal, Mr. Rahamin Haim  NaN
82                   McDermott, Miss. Brigdet Delia  NaN
87                    Slocovski, Mr. Selman Francis  NaN
95                      Shorney, Mr. Charles Joseph  NaN
101                Petroff, Mr. Pastcho ("Pentcho")  NaN
107                          Moss, Mr. Albert Johan  NaN
109                             Moran, Miss. Bertha  NaN
121                      Moore, Mr. Leonard Charles  NaN
126                             McMahon, Mr. Martin  NaN
128                               Peter, Miss. Anna  NaN
140                   Boulos, Mrs. Joseph (Sultana)  NaN
154                           Olsen, Mr. Ole Martin  NaN

In [37]:
# 'age'컬럼의 결측치를 age의 평균으로 채우기
titanic_df.Age.fillna(titanic_df.Age.mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: Age, Length: 156, dtype: float64

In [38]:
titanic_df.Age.isnull().sum()

np.int64(30)

In [39]:
# 'cabin'의 결측치를 'N'으로 채우고, 알파벳 한자리로 변경하기
# 'cabin' 컬럼의 결측치 확인
titanic_df.Cabin.isnull().sum()

np.int64(125)

In [40]:
# 'cabin'의 결측치를 'N'으로 채우기
titanic_df.Cabin = titanic_df.Cabin.fillna('N')
titanic_df.loc[4]

PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                                 N
Embarked                              S
Name: 4, dtype: object

In [41]:
titanic_df.Cabin.isnull().sum()

np.int64(0)

In [42]:
# 'cabin' 컬럼의 값 확인
titanic_df.Cabin.value_counts()

Cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [43]:
# 객실의 알파벳값만 남겨 놓기
titanic_df.Cabin.apply(lambda x : x[0])

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: Cabin, Length: 156, dtype: str

In [44]:
# 'embarked' 컬럼의 결측치 삭제