# 판다스(Pandas) - (1) 기본 사용법

### 1. 판다스 사용 준비

In [2]:
# 판다스 설치
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in D:\Lecture\Setup\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Lecture\Setup\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in D:\Lecture\Setup\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------- ----- 8.7/10.0 MB 47.0 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 45.8 MB/s  0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.5 tzdata-2026.3

In [6]:
# 판다스 import 하기
import pandas as pd

# 버전 확인
np.__version__

'3.0.5'

### 2. 시리즈 (Series)
* 객체 생성, 주요 속성 확인

In [7]:
numbers = [1, 2, 3, 4, 5]
# 시리즈 생성
sr1 = pd.Series(numbers)
sr1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# 속성 확인 : 데이터 타입, 행과 열의 수, 데이터 수, 이름
print(sr1.dtype, sr1.shape, sr1.size, sr1.name)

# 속성 확인 : 인덱스
print(sr1.index)

# 속성 확인 : 데이터 값
print(sr1.values)

In [24]:
numbers = [1, 2, 3, 4, 5]
# 실수형으로 시리즈 생성
sr2 = pd.Series(numbers, dtype=float)
sr2

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [25]:
chars = ['a', 'b', 'c', 'd', 'e']
# 시리즈 생성 시 index와 name 지정
sr3 = pd.Series(numbers, index=chars, name='MySeries')
sr3

# 속성 확인
sr3.dtype, sr3.name, sr3.index

(dtype('int64'), 'MySeries', Index(['a', 'b', 'c', 'd', 'e'], dtype='str'))

In [26]:
# 시리즈 생성 후에 index와 이름 추가하기
sr4 = pd.Series(numbers)
sr4.index = chars
sr4.name = 'MySeries'
sr4

a    1
b    2
c    3
d    4
e    5
Name: MySeries, dtype: int64

In [21]:
dict_data = {'a' : 1, 'b' : 2, 'c' : 3, 'd' : 4, 'e' : 5}
# dictionary로부터 시리즈 생성하기
dict_sr = pd.Series(dict_data)

# 속성 확인
print(dict_sr.index)
print(dict_sr.values)
    
dict_sr

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
[1 2 3 4 5]

a    1
b    2
c    3
d    4
e    5
dtype: int64

### 3. 데이터프레임 객체 생성, 주요 속성 확인

In [ ]:
numbers = [1, 2, 3, 4, 5]
# 리스트로부터 데이터프레임 생성
num_df = pd.DataFrame(numbers)

# 컬럼명 'number'를 지정하여 데이터프레임 생성
num_df = pd.DataFrame(numbers, columns = ['number'])

num_df

In [17]:
score=[['정약용', 70, 80, 100],
       ['이순신', 100, 80, 70],
       ['이율곡', 90, 95, 90]]

# 2차원 리스트로 부터 데이터프레이 생성
score_df = pd.DataFrame(score)

score_df

     0    1   2    3
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [18]:
# 데이터프레임에 컬럼명 추가하기
names = ['이름', '국어', '영어', '수학']
score_df.columns = names
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [19]:
# 데이터프레임 생성 시 컬럼명 추가하기
score_df2 = pd.DataFrame(score, columns = names)
score_df2

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [13]:
# 데이터프레임 속성 확인 : 행과열의 수, 인덱스, 컬럼명, 데이터타입, 데이터값
print(score_df.shape, score_df.index, score_df.columns)

(3, 4) RangeIndex(start=0, stop=3, step=1) Index(['name', 'korean', 'english', 'math'], dtype='str')

In [20]:
# 데이터프레임에 문자형 인덱스 추가하기
index = ['a', 'b', 'c']
score

[['정약용', 70, 80, 100], ['이순신', 100, 80, 70], ['이율곡', 90, 95, 90]]

In [9]:
# dictionary로부터 데이터프레임 생성하기

score_dict={'이름': ['정약용', '이순신', '이율곡'],
            '국어' : [70, 100, 90],
            '영어' : [80, 80, 95],
            '수학' : [100, 70, 90]}

score_df = pd.DataFrame(score_dict)
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [10]:
# '이름' 컬럼명을 'name'으로 변경하기
new_df = score_df.rename(columns={'이름':'name', '국어':'korean'})
new_df

  name  korean  영어   수학
0  정약용      70  80  100
1  이순신     100  80   70
2  이율곡      90  95   90

In [11]:
# 컬럼명을 모두 바꾸기 (영어로)
score_df.columns = ['name', 'korean', 'english', 'math']
score_df

  name  korean  english  math
0  정약용      70       80   100
1  이순신     100       80    70
2  이율곡      90       95    90

In [15]:
# '국어' 컬럼의 데이터의 실수형으로 변환하기
new_df = score_df.astype({'korean': float})
new_df

  name  korean  english  math
0  정약용    70.0       80   100
1  이순신   100.0       80    70
2  이율곡    90.0       95    90

In [29]:
# '이름' 컬럼의 index로 사용하기

In [ ]:
# '이름' 컬럼에 index 적용하기

In [ ]:
# index 초기화하기

### 4. 데이터프레임의 열 다루기 (추가, 삭제, 수정)

In [30]:
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [32]:
# '사회' 컬럼 추가
scores =[85, 88, 92]
score_df['사회'] = scores
score_df

    이름   국어  영어   수학  사회
0  정약용   70  80  100  85
1  이순신  100  80   70  88
2  이율곡   90  95   90  92

In [33]:
# 모든 칼럼의 값을 더해서 '총점' 칼럼 만들어 추가하기
score_df['총점'] = score_df['국어'] + score_df['영어'] + score_df['수학'] + score_df['사회']
score_df

    이름   국어  영어   수학  사회   총점
0  정약용   70  80  100  85  335
1  이순신  100  80   70  88  338
2  이율곡   90  95   90  92  367

In [34]:
# '평균' 칼럼 추가
score_df['평균'] = score_df['총점'] / 4
score_df

    이름   국어  영어   수학  사회   총점     평균
0  정약용   70  80  100  85  335  83.75
1  이순신  100  80   70  88  338  84.50
2  이율곡   90  95   90  92  367  91.75

In [ ]:
# 학생별 총점, 평균 구하기

In [36]:
# 빈 데이터프레임 만들고 컬럼 추가하기
x = [0, 1, 2, 3, 4, 5]
y = [0, 2, 4, 6, 8, 10]
df = pd.DataFrame()
df['x'] = x
df['y'] = y
df['x * y'] = df['x'] + df['y']
df

   x   y  x * y
0  0   0      0
1  1   2      3
2  2   4      6
3  3   6      9
4  4   8     12
5  5  10     15

### 5. 데이터프레임의 행/열 삭제

In [ ]:
score_df = pd.DataFrame(score, columns = ['이름', '국어', '영어', '수학'])
score_df

In [ ]:
# '이름' 칼럼 삭제

In [ ]:
score_df.drop([0, 2]) #, axis=0)

In [ ]:
new_df = score_df.drop(score_df.index[0])
new_df